-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  book_assets

CREATE TABLE IF NOT EXISTS book_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  asset_type TEXT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size_bytes BIGINT NOT NULL,
  storage_path TEXT NULL,
  content_hash VARCHAR(64) NULL,
  download_filename VARCHAR(255) NULL,
  is_encrypted BOOLEAN NOT NULL DEFAULT FALSE,
  encryption_algo VARCHAR(50) NULL,
  encryption_key_enc BYTEA NULL,
  encryption_iv  BYTEA NULL,
  encryption_tag BYTEA NULL,
  encryption_aad BYTEA NULL,
  encryption_meta JSONB NULL,
  key_version VARCHAR(64) NULL,
  key_id BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_asset_type CHECK (asset_type IN ('cover','pdf','epub','mobi','sample','extra'))
);
